# Generated by Django 4.1.13 on 2024-08-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginout0', '0013_remove_bookings_price_remove_bookings_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginout0.product'),
        ),
    ]
