# Generated by Django 4.1.13 on 2024-08-08 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginout0', '0014_alter_bookings_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginout0.product'),
        ),
    ]
