# Generated by Django 5.1.5 on 2025-02-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginout0', '0015_alter_bookings_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
