# Generated by Django 5.1.5 on 2025-02-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginout0', '0016_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='product_pictures/'),
        ),
    ]
